language: cpp

sudo: false
dist: xenial

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0

script:
  - ./contrib/setup-btor.sh
  - ./contrib/setup-cvc4.sh
  - ./configure.sh --btor --cvc4
  - cd build && make && make test
