language: cpp

sudo: false
dist: bionic

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0

env:
  - SOLVER="btor"
  - SOLVER="cvc4"

script:
  - bash -c "./contrib/setup-${SOLVER}.sh"
  - bash -c "./configure.sh --${SOLVER}"
  - cd build && make && make test
