language: cpp
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages: &common_deps
      - antlr3
      - cmake
      - cxxtest
      - junit4
      - libantlr3c-dev
      - libcln-dev
      - libgmp-dev
      - libhamcrest-java
      - openjdk-8-jdk
      - swig3.0

jobs:
  include:
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="btor" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: gcc
    - os: linux
      dist: bionic
      env: SOLVER="cvc4" OPTS=""
      compiler: clang
    - os: linux
      dist: bionic
      env: SOLVER="msat" OPTS="--auto-yes"
    - os: osx
      osx_image: xcode9
      env: SOLVER='btor' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='cvc4' OPTS=""
    - os: osx
      osx_image: xcode9
      env: SOLVER='msat' OPTS="--auto-yes"

script:
  - bash -c "./contrib/setup-${SOLVER}.sh ${OPTS}"
  - bash -c "./configure.sh --${SOLVER}"
  - cd build && make && make test
