# CMake generated Testfile for 
# Source directory: /home/zvi/smt-switch/tests
# Build directory: /home/zvi/smt-switch/pbv/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(example-8_test "/home/zvi/smt-switch/pbv/tests/example-8")
set_tests_properties(example-8_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;70;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(example-k_test "/home/zvi/smt-switch/pbv/tests/example-k")
set_tests_properties(example-k_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;71;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-array_test "/home/zvi/smt-switch/pbv/tests/test-array")
set_tests_properties(test-array_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;72;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-disjointset_test "/home/zvi/smt-switch/pbv/tests/test-disjointset")
set_tests_properties(test-disjointset_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;73;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-dt_test "/home/zvi/smt-switch/pbv/tests/test-dt")
set_tests_properties(test-dt_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;74;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-generic-solver_test "/home/zvi/smt-switch/pbv/tests/test-generic-solver")
set_tests_properties(test-generic-solver_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;75;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-generic-sort_test "/home/zvi/smt-switch/pbv/tests/test-generic-sort")
set_tests_properties(test-generic-sort_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;76;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-generic-term_test "/home/zvi/smt-switch/pbv/tests/test-generic-term")
set_tests_properties(test-generic-term_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;77;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-int_test "/home/zvi/smt-switch/pbv/tests/test-int")
set_tests_properties(test-int_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;78;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-itp_test "/home/zvi/smt-switch/pbv/tests/test-itp")
set_tests_properties(test-itp_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;79;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-logging-solver_test "/home/zvi/smt-switch/pbv/tests/test-logging-solver")
set_tests_properties(test-logging-solver_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;80;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-sorting-network_test "/home/zvi/smt-switch/pbv/tests/test-sorting-network")
set_tests_properties(test-sorting-network_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;81;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-term-translation_test "/home/zvi/smt-switch/pbv/tests/test-term-translation")
set_tests_properties(test-term-translation_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;82;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-unsat-core_test "/home/zvi/smt-switch/pbv/tests/test-unsat-core")
set_tests_properties(test-unsat-core_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;83;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-unsat-core-reducer_test "/home/zvi/smt-switch/pbv/tests/test-unsat-core-reducer")
set_tests_properties(test-unsat-core-reducer_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;84;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
add_test(test-variadic-ops_test "/home/zvi/smt-switch/pbv/tests/test-variadic-ops")
set_tests_properties(test-variadic-ops_test PROPERTIES  _BACKTRACE_TRIPLES "/home/zvi/smt-switch/tests/CMakeLists.txt;67;add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;85;switch_add_test;/home/zvi/smt-switch/tests/CMakeLists.txt;0;")
subdirs("googletest-build")
subdirs("unit")
